spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: xxx-dev
---
spring:
  profiles: uat
  application:
    name: xxx-uat
---
spring:
  profiles: test
  application:
    name: xxx-test